# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Shakya Deb Ganguly'
name:             'Shakya Deb Ganguly'
#tagline:          ''
description:      'Digital Consultant and Technologist'
#url:              https://cs-ox-wolf3794.github.io/
baseurl:
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Anjana Sofia Vakil'
  url:            vakila.github.io
  email:          'ganguly.sd@gmail.com'
  github:         'https://github.com/cs-ox-wolf3794'
  facebook:       'http://www.facebook.com/iwhozombie'
  twitter:        'https://twitter.com/iwhozombie'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/shakya-d-ganguly-ba8a3a21/'

paginate:         3
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cs-ox-wolf3794/cs-ox-wolf3794.github.io/

# Collections
collections:
  - projects
  - talks

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
